from pprint import pprint

events_47_list = \
"""EVT_APP_LCL_CELL_ADD_REQ
EVT_APP_LCL_CELL_ADD_RSP
EVT_APP_UE_RRC_RECONFIG_DELIVERY_INDICATION
EVT_CKW_UL_CONFIG_REQUEST
EVT_CTF_CONFIG_CONFIRM
EVT_EGTP_ADD_TUNNEL_REQUEST
EVT_EGTP_ADD_TUNNEL_RESPONSE
EVT_EGTP_INIT_REQUEST
EVT_EGTP_TTI_INDICATION
EVT_F1AP_MGMT_MSG_RX
EVT_F1AP_MGMT_MSG_TX
EVT_F1AP_UE_ID_REQUEST
EVT_F1AP_UE_ID_RESPONSE
EVT_F1AP_UE_MSG_RX
EVT_F1AP_UE_MSG_TX
EVT_KWU_DATA_INDICATION
EVT_KWU_DATA_REQUEST
EVT_NRUP_ADD_RAB_REQUEST
EVT_NRUP_ADD_RAB_RESPONSE
EVT_NRUP_EGTPU_DATA_INDICATION
EVT_OAM_CELL_CONFIG_REQUEST
EVT_OAM_DU_CONFIG_REQUEST
EVT_RGR_LVL1_CCCH_DATA_INDICATION
EVT_RGR_LVL1_CONFIG_CONFIRM
EVT_RGR_LVL1_SI_CONFIG_CONFIRM
EVT_RGR_LVL1_TTI_INDICATION
EVT_RGR_LVL2_CONFIG_CONFIRM
EVT_RLC_FLW_CTRL_INFO_INDICATION
EVT_RLC_REQ_FLW_CTRL_INFO
EVT_RLC_UE_CONFIG_CONFIRM
EVT_RRM_CELL_ADD_CONFIRM
EVT_RRM_CELL_ADD_REQUEST
EVT_RRM_UE_ADMIT_CONFIRM
EVT_RRM_UE_ADMIT_REQUEST
EVT_RRM_UE_RECONFIG_REQUEST
EVT_RRM_UE_RECONFIG_RESPONSE
EVT_SCTP_ASSOC_STATUS
EVT_SCTP_CONFIG_REQUEST
EVT_SCTP_CONFIG_RESPONSE
EVT_SCTP_USER_PAYLOAD_INDICATION
EVT_SCTP_USER_PAYLOAD_REQUEST
EVT_TIMER_TICK_INDICATION
EVT_UDX_CONFIG_CONFIRM
EVT_UDX_CONFIG_REQUEST
EVT_UDX_DL_CLEANUP_MEM
EVT_UDX_STA_PDU_REQUEST
EVT_UDX_STA_UPD_REQUEST"""

events_47_list = events_47_list.split('\n')
# pprint(events_47_list)
# print(len(events_47_list))

events_46_list = ['EVT_UDX_STA_UPD_REQUEST', 'EVT_UDX_STA_PDU_REQUEST', 'EVT_UDX_DL_CLEANUP_MEM',
                  'EVT_UDX_CONFIG_REQUEST', 'EVT_UDX_CONFIG_CONFIRM', 'EVT_TIMER_TICK_INDICATION',
                  'EVT_SCTP_USER_PAYLOAD_REQUEST', 'EVT_SCTP_USER_PAYLOAD_INDICATION', 'EVT_SCTP_CONFIG_RESPONSE',
                  'EVT_SCTP_CONFIG_REQUEST', 'EVT_SCTP_ASSOC_STATUS', 'EVT_RRM_UE_RECONFIG_RESPONSE',
                  'EVT_RRM_UE_RECONFIG_REQUEST', 'EVT_RRM_UE_ADMIT_REQUEST', 'EVT_RRM_UE_ADMIT_CONFIRM',
                  'EVT_RRM_CELL_ADD_REQUEST', 'EVT_RRM_CELL_ADD_CONFIRM', 'EVT_RLC_UE_CONFIG_CONFIRM',
                  'EVT_RGR_LVL2_CONFIG_CONFIRM', 'EVT_RGR_LVL1_TTI_INDICATION', 'EVT_RGR_LVL1_SI_CONFIG_CONFIRM',
                  'EVT_RGR_LVL1_PAGING_CONFIRM', 'EVT_RGR_LVL1_CONFIG_CONFIRM', 'EVT_RGR_LVL1_CCCH_DATA_INDICATION',
                  'EVT_OAM_DU_CONFIG_REQUEST', 'EVT_OAM_CELL_CONFIG_REQUEST', 'EVT_NRUP_EGTPU_DATA_INDICATION',
                  'EVT_NRUP_ADD_RAB_RESPONSE', 'EVT_NRUP_ADD_RAB_REQUEST', 'EVT_KWU_DATA_REQUEST',
                  'EVT_KWU_DATA_INDICATION', 'EVT_F1AP_UE_MSG_TX', 'EVT_F1AP_UE_MSG_RX', 'EVT_F1AP_UE_ID_RESPONSE',
                  'EVT_F1AP_UE_ID_REQUEST', 'EVT_F1AP_MGMT_MSG_TX', 'EVT_F1AP_MGMT_MSG_RX', 'EVT_EGTP_TTI_INDICATION',
                  'EVT_EGTP_INIT_REQUEST', 'EVT_EGTP_ADD_TUNNEL_RESPONSE', 'EVT_EGTP_ADD_TUNNEL_REQUEST',
                  'EVT_CTF_CONFIG_CONFIRM', 'EVT_CKW_UL_CONFIG_REQUEST', 'EVT_APP_UE_RRC_RECONFIG_DELIVERY_INDICATION',
                  'EVT_APP_LCL_CELL_ADD_RSP', 'EVT_APP_LCL_CELL_ADD_REQ']


for event in events_46_list:
    if event not in events_47_list:
        print(event)
