from pprint import pprint

"""
# SS_RT_EVT
- EVT_TFU_RA_REQUEST_INDICATION
- EVT_TFU_CRC_INDICATION
- EVT_UDX_STA_PHBT_START_TIMER
- EVT_L1_MSG_INDICATION
- EVT_COMMON_UE_ACK_INDICATION
- EVT_RGR_LVL1_CONFIG_REQUEST
- EVT_CTF_CONFIG_REQUEST
- EVT_KW_UMUL_REASSEMBLE_TIMER
- EVT_RGR_LVL2_CONFIG_REQUEST
- EVT_KW_AMUL_STA_PROH_TIMER
- EVT_RGR_LVL1_CCCH_DATA_REQUEST
- EVT_RGR_LVL1_SI_CONFIG_REQUEST
- EVT_COMMON_UE_ACK_INDICATION

# SS_NRT_EVT
- EVT_SCTP_USER_PAYLOAD_INDICATION
- EVT_SCTP_CONFIG_REQUEST
- EVT_UDX_STA_PHBT_START_TIMER
- EVT_F1AP_UE_ID_REQUEST
- EVT_APP_LCL_CELL_ADD_RSP
- EVT_APP_UE_RRC_RECONFIG_DELIVERY_INDICATION
- EVT_TFU_RA_REQUEST_INDICATION
- EVT_COMMON_UE_ACK_INDICATION
- EVT_UDX_STA_PDU_REQUEST
- EVT_SCTP_USER_PAYLOAD_REQUEST
- EVT_RRM_CELL_ADD_CONFIRM
- EVT_F1AP_MGMT_MSG_TX
- EVT_CTF_CONFIG_REQUEST
- EVT_TIMER_TICK_INDICATION
- EVT_KWU_DATA_INDICATION
- EVT_LVL_INF_START_INDICATION
- EVT_UDX_DL_CLEANUP_MEM
- EVT_RLC_FLW_CTRL_INFO_INDICATION
- EVT_RGR_LVL1_CCCH_DATA_INDICATION
- EVT_NRUP_EGTPU_DATA_INDICATION
- EVT_RLC_UE_CONFIG_CONFIRM
- EVT_RGR_LVL2_CONFIG_REQUEST
- EVT_RGR_LVL1_CONFIG_REQUEST
- EVT_RGR_LVL1_CCCH_DATA_REQUEST
- EVT_KW_UMUL_REASSEMBLE_TIMER
- EVT_RRM_UE_RECONFIG_RESPONSE
- EVT_F1AP_UE_MSG_TX
- EVT_CTF_CONFIG_CONFIRM
- EVT_RRM_UE_RECONFIG_REQUEST
- EVT_KW_AMUL_STA_PROH_TIMER
- EVT_RRM_UE_ADMIT_REQUEST
- EVT_CKW_UL_CONFIG_REQUEST
- EVT_RGR_LVL1_SI_CONFIG_REQUEST
- EVT_OAM_DU_CONFIG_REQUEST
- EVT_TFU_CRC_INDICATION
- EVT_RGR_LVL1_TTI_INDICATION
- EVT_F1AP_UE_ID_RESPONSE
- EVT_F1AP_UE_MSG_RX
- EVT_NRUP_ADD_RAB_REQUEST
- EVT_NRUP_ADD_RAB_RESPONSE
- EVT_APP_LCL_CELL_ADD_REQ
- EVT_RGR_LVL1_CONFIG_CONFIRM
- EVT_OAM_CELL_CONFIG_REQUEST
- EVT_L1_MSG_INDICATION
- EVT_RLC_REQ_FLW_CTRL_INFO
- EVT_RRM_CELL_ADD_REQUEST
- EVT_EGTP_TTI_INDICATION
- EVT_F1AP_MGMT_MSG_RX
- EVT_UDX_CONFIG_CONFIRM
- EVT_EGTP_ADD_TUNNEL_RESPONSE
- EVT_UDX_STA_UPD_REQUEST
- EVT_EGTP_INIT_REQUEST
- EVT_UDX_CONFIG_REQUEST
- EVT_SCTP_ASSOC_STATUS
- EVT_SCTP_CONFIG_RESPONSE
- EVT_RGR_LVL2_CONFIG_CONFIRM
- EVT_KWU_DATA_REQUEST
- EVT_EGTP_ADD_TUNNEL_REQUEST
- EVT_RRM_UE_ADMIT_CONFIRM
- EVT_APP_LCL_CELL_ADD_REQ
- EVT_RGR_LVL1_SI_CONFIG_CONFIRM
- EVT_INF_SLOT_ALLOC_REQUEST

# QUEUE RT EVT
- EVT_TFU_RA_REQUEST
- EVT_RGR_LVL1_CONFIG
- EVT_COMMON_UE_ACK
- EVT_KW_UMUL_REASSEMBLE
- EVT_KW_AMUL_STA_PROH
- EVT_RGR_LVL1_CCCH_DATA
- EVT_CTF_CONFIG
- EVT_COMMON_UE_ACK
- EVT_UDX_STA_PHBT_START
- EVT_RGR_LVL2_CONFIG
- EVT_L1_MSG
- EVT_TFU_CRC
- EVT_RGR_LVL1_SI_CONFIG



"""


def stats_all_events(fileName):
    with open(f'{fileName}', 'r') as fp:
        lines = fp.readlines()
    all_events = list(set(lines))
    for i in range(len(all_events)):
        print(all_events[i].strip())


if __name__ == '__main__':
    fille_name = '所有事件.txt'
    stats_all_events(fileName=fille_name)
